name       : mysql-connector-cpp
version    : 8.0.12
release    : 3
source     :
    - https://dev.mysql.com/get/Downloads/Connector-C++/mysql-connector-c++-8.0.12-src.tar.gz : 47d9f152988fe205350a6d31d032692a6777f838a886c3b3dc7af3b0652fdd50
license    : GPL-2.0-only
component  : programming.library
summary    : MySQL database connector for C++
description: |
    MySQL Connector/C++ is a MySQL database connector for C++. It lets you develop C++ applications that connect to the MySQL Server.
builddeps  :
    - pkgconfig(mariadb)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/001-fix-mariadb.patch
    %cmake -DINSTALL_DOCS=/usr/share/doc/mysql-connector-cpp
build      : |
    %make
install    : |
    %make_install
