name       : mysql-connector-cpp
version    : 1.1.9
release    : 4
source     :
    - https://github.com/mysql/mysql-connector-cpp/archive/1.1.9.tar.gz : f421d3106a1b91b29a234ab145108b0f4ef882069744cb57aa492fedbba5c54e
license    : GPL-2.0-only
component  : programming.library
summary    : MySQL database connector for C++
description: |
    MySQL Connector/C++ is a MySQL database connector for C++. It lets you develop C++ applications that connect to the MySQL Server.
builddeps  :
    - pkgconfig(mariadb)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/001-fix-mariadb.patch
    %cmake -DINSTALL_DOCS=/usr/share/doc/mysql-connector-cpp
build      : |
    %make
install    : |
    %make_install
    rm %installroot%%libdir%/libmysqlcppconn-static.a
    rm %installroot%/usr/{COPYING,Licenses_for_Third-Party_Components.txt,README}
