name       : mysql-connector-cpp
version    : 1.1.9
release    : 2
source     :
    - https://dev.mysql.com/get/Downloads/Connector-C++/mysql-connector-c++-1.1.9.tar.gz : 3e31847a69a4e5c113b7c483731317ec4533858e3195d3a85026a0e2f509d2e4
license    : GPL-2.0-only
component  : programming.library
summary    : MySQL database connector for C++
description: |
    MySQL Connector/C++ is a MySQL database connector for C++. It lets you develop C++ applications that connect to the MySQL Server.
builddeps  :
    - pkgconfig(mariadb)
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/001-fix-mariadb.patch
    %cmake -DINSTALL_DOCS=/usr/share/doc/mysql-connector-cpp
build      : |
    %make
install    : |
    %make_install
    rm %installroot%%libdir%/libmysqlcppconn-static.a
    rm %installroot%/usr/{COPYING,Licenses_for_Third-Party_Components.txt,README}
