name       : mysql-connector-cpp
version    : 8.0.20
release    : 6
source     :
    - https://github.com/mysql/mysql-connector-cpp/archive/8.0.20.tar.gz : b2fb4d18548f30173176bfe5e644b0b690493e15189e48d4de6e53bf7d499631
license    : GPL-2.0-only
component  : programming.library
summary    : MySQL database connector for C++
description: |
    MySQL Connector/C++ is a MySQL database connector for C++. It lets you develop C++ applications that connect to the MySQL Server.
builddeps  :
    - pkgconfig(mariadb)
    - libboost-devel
setup      : |
    %cmake -DINSTALL_DOCS=/usr/share/doc/mysql-connector-cpp
build      : |
    %make
install    : |
    %make_install
    rm %installroot%/usr/INFO*
